#default: &default
#  url: redis://localhost:6379
#  db: 0

#development:
#  <<: *default

#test:
#  <<: *default

#production:
#  <<: *default
#  url: redis://somehost:6379

development:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: 6379
  thread_safe: true
  timeout: 60

test:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: 6379
  thread_safe: true
  timeout: 60

production:
  url: redis://h:p41a9009364372e895a3a4d5775a94010d7ce4ea1b57bc5360130178f6ef83027@ec2-54-161-255-142.compute-1.amazonaws.com:20429

  host: "ec2-54-161-255-142.compute-1.amazonaws.com"
  #port: 20429
  #user: h
  password: p41a9009364372e895a3a4d5775a94010d7ce4ea1b57bc5360130178f6ef83027
